// Re-export from PodcastPreviewShared for backward compatibility
import PodcastPreviewShared

public typealias RemoteMachineIdentity = PodcastPreviewShared.RemoteMachineIdentity
public typealias CompanionTint = PodcastPreviewShared.CompanionTint
public typealias CompanionKeyValueRow = PodcastPreviewShared.CompanionKeyValueRow
public typealias CompanionSummaryChip = PodcastPreviewShared.CompanionSummaryChip
public typealias CompanionSeries = PodcastPreviewShared.CompanionSeries
public typealias CompanionDashboardCardKind = PodcastPreviewShared.CompanionDashboardCardKind
public typealias CompanionDashboardCard = PodcastPreviewShared.CompanionDashboardCard
public typealias CompanionDashboardSection = PodcastPreviewShared.CompanionDashboardSection
public typealias CompanionDashboardSnapshot = PodcastPreviewShared.CompanionDashboardSnapshot
public typealias CompanionLiveCPUSnapshot = PodcastPreviewShared.CompanionLiveCPUSnapshot
public typealias CompanionLiveGPUSnapshot = PodcastPreviewShared.CompanionLiveGPUSnapshot
public typealias CompanionLiveMemorySnapshot = PodcastPreviewShared.CompanionLiveMemorySnapshot
public typealias CompanionLiveStorageSnapshot = PodcastPreviewShared.CompanionLiveStorageSnapshot
public typealias CompanionLiveNetworkSnapshot = PodcastPreviewShared.CompanionLiveNetworkSnapshot
public typealias CompanionLivePowerSnapshot = PodcastPreviewShared.CompanionLivePowerSnapshot
public typealias CompanionLiveANESnapshot = PodcastPreviewShared.CompanionLiveANESnapshot
public typealias CompanionLiveMediaSnapshot = PodcastPreviewShared.CompanionLiveMediaSnapshot
public typealias CompanionLiveProcessSnapshot = PodcastPreviewShared.CompanionLiveProcessSnapshot
public typealias CompanionLiveSnapshot = PodcastPreviewShared.CompanionLiveSnapshot
public typealias CompanionCurrentSnapshotPayload = PodcastPreviewShared.CompanionCurrentSnapshotPayload
public typealias CompanionTimelineBucket = PodcastPreviewShared.CompanionTimelineBucket
public typealias CompanionTimelineSeriesPayload = PodcastPreviewShared.CompanionTimelineSeriesPayload
public typealias CompanionTimelinePayload = PodcastPreviewShared.CompanionTimelinePayload
public typealias CompanionProcessRollupPayload = PodcastPreviewShared.CompanionProcessRollupPayload
public typealias CompanionHardwareEventPayload = PodcastPreviewShared.CompanionHardwareEventPayload
